# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: INTRODUCTION
    url: /
    weight: 10
  - name: MEMEBERS
    url: /#papers
    weight: 11
  - name: RESEARCH
    url: /#talks
    weight: 12
  - name: PUBLICATION
    url: /#news
    weight: 13
  - name: INSTRUMENT
    url: experience/
    weight: 20
  - name: BOARD
    url: projects/
    weight: 30
